baseurl = "http://vimagick.github.io/www/"
canonifyurls = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"

[params]
description = "hello world"
copyright = "datageek™"

[[menu.main]]
name = "Youtube"
url = "https://www.youtube.com"
